### ISSUE TITLE
39R vs 4k7

### ISSUE THREAD

**Issue by jordens** [sinara-hw/Banker_VHDCI_2_EDGE_Buffered#1]
Why are the 39R power resistors on the VHDCI side and the 4k7 resistors on the EDGE sides and why not the other way around? The other edge modules have 39R in series, as does Banker. Is 4k7 not a bit high to drive "generic" SMA/BNC/D-SUB lines?

**Comment by gkasprow** [comment]
These 4K7 are pulldown resistors that keep the logic level low when an input is floating.

**Comment by jordens** [comment]
Right. My bad.
